### ISSUE TITLE
Collaboration for this EIP

### ISSUE THREAD

**Issue by itschaindev** [Nerolation/EIP-ERC-721-Stealth-Addresses#1]
Hi! 

I would like to help in drafting this EIP. Of lately, I've been looking into privacy aspects of ENS. Also, [app.umbra.cash](https://app.umbra.cash/) is an interesting project utilising stealth addresses.

Let me know how you would like to proceed on this.
Thanks!
Jagrut

**Comment by nerolation** [comment]
The EIP is already drafted, check it out here https://github.com/ethereum/EIPs/blob/master/EIPS/eip-5564.md .
I'm currently trying to form a group that may implement the EIP into some SM wallet application.

If you think you can contribute there, please dm contact me on twitter or mail for further info, every help is very appreciated!
