### ISSUE TITLE
EllipticCurve.sol contract not found

### ISSUE THREAD

**Issue by lucianoacsilva** [Nerolation/EIP-ERC-721-Stealth-Addresses#19]
Hello,

Where is the **EllipticCurve.sol** contract file located? It is imported in some other contracts and call scripts, but I could not locate it within the repository.

Best regards

Luciano Augusto

**Comment by nerolation** [comment]
I think we used this file here (though, it's only for testing purposes as the contract isn't needed for the ERC):
https://github.com/witnet/elliptic-curve-solidity/tree/master/contracts
